apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapp
    env: estudo
  name: webapp-svc
  namespace: estudo-felipe
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: webapp
  type: ClusterIP
status:
  loadBalancer: {}
