apiVersion: v1
kind: Pod
metadata:
  labels:
    app: meu-pod
  name: meu-pod
  namespace: estudo
spec:
  containers:
  - image: nginx:1.27
    name: meu-pod
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi 
