apiVersion: v1
kind: Pod
metadata:
  name: app-com-sidecar
  namespace: estudo
spec:
  containers:
    - name: app
      image: nginx:1.27
      volumeMounts:
        - name: logs
          mountPath: /var/log/nginx
    - name: log-shipper
      image: fluent/fluent-bit:3.0
      volumeMounts:
        - name: logs
          mountPath: /var/log/nginx
      env:
        - name: FLUENT_CONF
          value: /fluent-bit/etc/fluent-bit.conf
  volumes:
    - name: logs
      emptyDir: {}
